config/routes.rb
Assignment::Application.routes.draw do

  get "cart/index"

  get "product/show"

  get "yahootest/index"

  root to: "home#home"
  get "register", to: "user#register"
  post "register", to: "user#create"
  get "login", to: "user#login"
  post "login", to: "user#login_check"
  get "logout", to: "user#logout"
  get "profile", to: "user#profile"
  get "usercp", to: "user#usercp"
  put "usercp", to: "user#update"

  get "yahootest", to:"yahootest#index"

  get "category", to: "home#home"
  get "category/:categoryid", to: "category#show"
  get "category/:categoryid/:page", to: "category#show"

  get "product/add", to: "product#add"
  post "product/add", to: "product#create"
  get "product/:productid", to: "product#show"

  get "product", to: "category#search"

  get "user-products", to: "category#user_products"
  get "user-products/:page", to: "category#user_products"

  get "cart", to: "cart#index"
  get "cart/add/:productid/:quantity", to: "cart#create"
  get "cart/edit/:productid/:quantity", to: "cart#edit"
  get "cart/delete/:productid", to: "cart#delete"
  get "cart/empty", to: "cart#empty"
  get "cart/purchase", to: "cart#purchase"

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    require_user (cart_index_path) or return
    @products = Product.find_by_sql "SELECT * FROM cartitems AS CI LEFT JOIN (SELECT p.id, p.name, p.price_value, p.price_currency FROM products AS p) AS P ON CI.product_id=P.id WHERE CI.user_id=#{session[:userid]}"
  end
  def create
    if get_user.nil?
      return render json: {errorCode:1}
    end
    product_id = params[:productid].to_i
    quantity = params[:quantity].to_i

    product = Product.find_by_id (product_id)
    if product.nil?
      return render json: {errorCode:2}
    end
    cartitem_existed = Cartitem.find(:first, conditions:['product_id=' + product_id.to_s, 'user_id=' + @user.id.to_s])
    if cartitem_existed.nil?
      cartitem = Cartitem.new ({user_id: @user.id, product_id: product.id, quantity: quantity})
      if cartitem.save
        return render json: {errorCode:0, successCode:1}
      else
        return render json: {errorCode:3}
      end
    else
      cartitem_existed[:quantity] += quantity

      if cartitem_existed.save
        return render json: {errorCode:0, successCode:2}
      else
        return render json: {errorCode:3}
      end
    end
  end

  def edit
    if get_user.nil?
      return render json: {errorCode:1}
    end
    product_id = params[:productid].to_i
    quantity = params[:quantity].to_i

    cartitem_existed = Cartitem.find(:first, conditions:['product_id=' + product_id.to_s, 'user_id=' + @user.id.to_s])
    if cartitem_existed.nil?
      return render json: {errorCode:2}
    else
      cartitem_existed[:quantity] = quantity

      if cartitem_existed.save
        return render json: {errorCode:0, successCode:1}
      else
        return render json: {errorCode:3}
      end
    end
  end

  def delete
    if get_user.nil?
      return render json: {errorCode:1}
    end
    product_id = params[:productid].to_i
    Cartitem.where(product_id: product_id, user_id: @user.id).destroy_all
    render json: {}
  end

  def empty
    if get_user.nil?
      cookie_flash_add(error: "You haven't loged in yet!")
      return redirect_to root_path
    else
      Cartitem.where(user_id: @user.id).delete_all
      cookie_flash_add(success: "You have emptyed your Cart.")
      return redirect_to root_path
    end
  end

  def purchase
    if get_user.nil?
      cookie_flash_add(error: "You haven't loged in yet!")
      return redirect_to root_path
    else
      UserMailer.purchase(@user).deliver
      # Cartitem.where(user_id: @user.id).delete_all
      cookie_flash_add(success: "Thanks for purchasing! We have just sent you an email.")
      return redirect_to root_path
    end
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/index.html.erb
<% provide(:title, "Your Cart") %>
<div class="row">
    <%= render('layouts/categories') %>
    <div class="span9">
        <ul class="breadcrumb">
            <li><%= link_to 'ホーム', root_url%><span class="divider">/</span></li>
            <li>Your Cart</li>
        </ul>

        <%if !@products.empty? %>
        <table class="table table-considered table-hover">
            <thead>
            <tr>
                <th>Product Name</th>
                <th align="right">Quantity</th>
                <th align="right" colspan="3">Price</th>
            </tr>
            </thead>
            <tbody>
            <%
            i=0
            total_money = 0
             @products.each do |product|
                total_money += product[:price_value]*product[:quantity]
                i += 1 %>
            <tr>
                <td><%=i%>. <%=link_to product[:name], controller:'product', action:'show', productid: product[:id]%></td>
                <td align="right">
                    <div class="span2 cart_edit input-append" align='right' onclick="event.stopPropagation()">
                      <input type="text" name="quantity" class="cartNum" value='<%= product[:quantity]%>'>
                      <button class="btn cartBtn" product-id="<%=product[:id]%>">Edit</button>
                    </div>
                </td>
                <td align="right"><%= product[:price_value]*product[:quantity]%><%= product[:quantity]%> </td>
                <td><%= product[:price_currency]%></td>
                <td><button class="btn btn-danger cartDeleteBtn" product-id="<%=product[:id]%>">Delete</button></td>
            </tr>
            <% end %>
            </tbody>
        </table>
            <div align="right">Total: <%=total_money%> JPY <br/><button class="btn" onclick="location.href='<%= cart_empty_path %>'">Empty <span class="icon-shopping-cart"></span></button> <button class="btn btn-primary" onclick="location.href='<%= cart_purchase_path %>'">Purchase</button></div>
        <% else %>
        <p> You don't have anything in your cart. Let's go around and pick something :).</p>
        <% end %>

    </div>
</div>