config/routes.rb
Assignment::Application.routes.draw do

  get "cart/index"

  get "product/show"

  get "yahootest/index"

  root to: "home#home"
  get "register", to: "user#register"
  post "register", to: "user#create"
  get "login", to: "user#login"
  post "login", to: "user#login_check"
  get "logout", to: "user#logout"
  get "profile", to: "user#profile"
  get "usercp", to: "user#usercp"
  put "usercp", to: "user#update"

  get "yahootest", to:"yahootest#index"

  get "category", to: "home#home"
  get "category/:categoryid", to: "category#show"
  get "category/:categoryid/:page", to: "category#show"

  get "product/add", to: "product#add"
  post "product/add", to: "product#create"
  get "product/:productid", to: "product#show"

  get "product", to: "category#search"

  get "user-products", to: "category#user_products"
  get "user-products/:page", to: "category#user_products"

  get "cart", to: "cart#index"
  get "cart/add/:productid/:quantity", to: "cart#create"
  get "cart/edit/:productid/:quantity", to: "cart#edit"
  get "cart/delete/:productid", to: "cart#delete"
  get "cart/empty", to: "cart#empty"
  get "cart/purchase", to: "cart#purchase"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :salt
  has_secure_password
  
  before_validation do |user|
  	user.email = user.email.downcase
  end

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with:VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true
  validates :password_confirmation, presence:true

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def register
    if session[:userid]
      @user = User.find_by_id(session[:userid])
      if @user
        cookie_flash_add notice: "You've already loged in."
        redirect_to root_url and return;
      end
    end
  	@user ||= User.new
  	def @user.flag
  		"register"
  	end
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		flash[:success] = "You have been registered successfully, have fun!"
  		session[:userid] = @user.id
      redirect_to root_url
  	else
  		render 'register'
  	end
  end

  def login
  	@user = User.new
  end

  def login_check
    user = User.find_by_email(params[:user][:email].downcase)
    if (user && user.authenticate(params[:user][:password]))
      session[:userid] = user.id
      cookie_flash_add(success: "Login successfully!")
      redirect_to params[:referer]
    else
      cookie_flash_add(error: "Login fail, please try again!")
      backup_referer params[:referer]
      redirect_to action: 'login'
    end
  end

  def logout
    if session[:userid]
      reset_session
      flash[:success] = "Loging out sucessfully!"
    else
      cookie_flash_add(error: "You haven't login yet!")
    end
    redirect_to root_url
  end

  def profile
    require_user profile_path
  end

  def update
    if session[:userid]
      @user = User.find_by_id(session[:userid])
      if @user
        if @user.authenticate(params[:user][:old_password])
          params[:user].delete(:old_password)
          if !@user.update_attributes(params[:user])
            render 'usercp'
            return
          end
          cookie_flash_add(success: "Your Password updated successfully!")
          redirect_to action: 'profile'
        else
          cookie_flash_add(error: "Your old Password isn't correct!")
          redirect_to action: 'usercp'
        end
      else
        cookie_flash_add(notice: "You haven't login yet!")
        redirect_to action: 'login'
      end
    else
      cookie_flash_add(error: "You haven't login yet!")
      redirect_to root_url
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
	def get_user
		@user ||=	if !session[:userid] then nil else User.find_by_id(session[:userid]) end
		@user
	end
  def require_user path
    if !session[:userid]
      cookie_flash_add(notice: "You haven't login yet!")

      if path == :default
        backup_referer :session
      else
        backup_referer path
      end

      redirect_to controller:'user', action: 'login'
      false
    else
      true
    end
  end
end

app/views/user/create.html.erb
<h3>AAAAAAAAAaaaaaaaaa</h3>

app/views/user/login.html.erb
<% provide(:title, "Login") %>
<div class="row">
	<div class="span6 offset3">
		<h3 align="center">User Login</h3>
		<%= form_for @user, url: login_path, html: {id: "user_login_form", align: "center", class: "form-horizontal"} do |u| %>
		<div class="control-group">
			<%= u.label :email, class: "control-label" %>
			<div class="controls"><%= u.text_field :email, placeholder: "username@example.com" %></div>
		</div>
		<div class="control-group">
			<%= u.label :password, class: "control-label" %>
			<div class="controls"><%= u.password_field :password %></div>
		</div>
			<div class="controls"><%= u.submit "Login", class: "btn btn-primary" %><input type="hidden" name="referer" value="<%= if session['referer']!='none' then session['referer'] else root_url end %>"></div>
		<% end %>
	</div>
</div>

app/views/user/profile.html.erb
<% provide(:title, "Profile") %>
<div class="row">
		<h3 align="center">Your Profile</h3>
		<div class="span1 offset3">Email</div>
		<div class="span5"><%= @user.email['@'] = ' at '; get_user.email %> - <%= link_to "Edit", usercp_path %></div>
</div>

app/views/user/register.html.erb
<% provide(:title, "Register") %>
<div class="row">
	<div class="span6 offset3">
		<h3 align="center">User Registration</h3>
		<%= @error = @user; render("layouts/error_messages") %>
		<%= form_for @user, url: register_path, html: {id: "user_register_form", align: "center", class: "form-horizontal"} do |u| %>
		<div class="control-group">
			<%= u.label :email, class: "control-label" %>
			<div class="controls"><%= u.text_field :email, placeholder: "username@example.com" %></div>
		</div>
		<div class="control-group">
			<%= u.label :password, class: "control-label" %>
			<div class="controls"><%= u.password_field :password %></div>
		</div>
		<div class="control-group">
			<%= u.label :password_confirmation, "Retype Password", class: "control-label" %>
			<div class="controls"><%= u.password_field :password_confirmation %></div>
		</div>
			<div class="controls"><%= u.submit "Register", class: "btn btn-primary" %> <%= button_tag 'Reset', type: 'reset', class: "btn" %><input type="hidden" name="flag" value="register"></div>
		<% end %>
	</div>
</div>

app/views/user/usercp.html.erb
<% provide(:title, "Edit Your Profile") %>
<div class="row">
	<div class="span6 offset3">
		<h3 align="center">Edit Your Profile</h3>
		<%= render("layouts/error_messages") %>
		<%= form_for get_user, url: usercp_path, html: {id: "user_register_form", align: "center", class: "form-horizontal"} do |u| %>
		<div class="control-group">
			<%= u.label :email, class: "control-label" %>
			<div class="controls"><%= u.text_field :email, placeholder: "username@example.com", disabled: "disabled" %></div>
		</div>
		<div class="control-group">
			<%= u.label :old_password, class: "control-label" %>
			<div class="controls"><%= u.password_field :old_password %></div>
		</div>
		<div class="control-group">
			<%= u.label :password, "New Password", class: "control-label" %>
			<div class="controls"><%= u.password_field :password %></div>
		</div>
		<div class="control-group">
			<%= u.label :password_confirmation, "Retype Password", class: "control-label" %>
			<div class="controls"><%= u.password_field :password_confirmation %></div>
		</div>
			<div class="controls"><%= u.submit "Update", class: "btn btn-primary" %> <%= button_tag 'Reset', type: 'reset', class: "btn" %><input type="hidden" name="flag" value="register"></div>
		<% end %>
	</div>
</div>